/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Meeting2026RouteImport } from './routes/meeting-2026'
import { Route as IndexRouteImport } from './routes/index'

const Meeting2026Route = Meeting2026RouteImport.update({
  id: '/meeting-2026',
  path: '/meeting-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meeting-2026': typeof Meeting2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meeting-2026': typeof Meeting2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meeting-2026': typeof Meeting2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meeting-2026'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meeting-2026'
  id: '__root__' | '/' | '/meeting-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Meeting2026Route: typeof Meeting2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meeting-2026': {
      id: '/meeting-2026'
      path: '/meeting-2026'
      fullPath: '/meeting-2026'
      preLoaderRoute: typeof Meeting2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Meeting2026Route: Meeting2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
